### ISSUE TITLE
need some flow example

### ISSUE THREAD

**Issue by programervn** [JRF63/DTLS-Test#1]
Dear Joseph,
How can I send response message from server after received message client?
follow is my code, but I did not work
char buf[1024];
    while (!SSL_get_shutdown(ssl)) {
        int read = SSL_read(ssl, buf, sizeof(buf));
        if (read > 0) {
            printf("%s\n", buf);
        }
    }
    //try to send response after received message from client
    char resp[1024];
    strcpy(resp, "server received");
    SSL_write(ssl, resp, strlen(resp) + 1);

    SSL_shutdown(ssl);

**Comment by JRF63** [comment]
The SSL_write should be inside the while loop.

I pushed a new version, can you see if it does what you want?

**Comment by programervn** [comment]
Dear Joseph,
It works.
Thanks
